import type {
  Evaluation, ExportItem, Job, ParamSpec, Region, Run, Session, StepRecord, StepSummary, ValidationReport,
} from "@/api/types";

export const region: Region = {
  id: "reg_1",
  name: "campus",
  description: "UCL campus, Aria glasses",
  vpr: { method: "cosplace", backbone: "ResNet18", dim: 256 },
  image_size: [512, 288],
  created_at: "2026-09-18T10:00:00+00:00",
  head: null,
  session_count: 1,
  run_count: 0,
};

const validReport: ValidationReport = {
  ok: true,
  num_frames: 12,
  has_gt: false,
  has_gps: false,
  has_iqa: true,
  descriptor_dim: 256,
  files: [
    { name: "poses.txt", required: true, status: "ok", lines: 12, detail: "" },
    { name: "timestamps.txt", required: true, status: "ok", lines: 12, detail: "" },
    { name: "intrinsics.txt", required: true, status: "ok", lines: 12, detail: "" },
    { name: "gps_data.txt", required: true, status: "ok", lines: 12, detail: "all zero" },
    { name: "database_descriptors.txt", required: true, status: "ok", lines: 12, detail: "dim 256" },
    { name: "poses_abs_gt.txt", required: false, status: "missing", lines: null, detail: "" },
    { name: "iqa_data.txt", required: false, status: "ok", lines: 12, detail: "" },
    { name: "edges_covis.txt", required: false, status: "ok", lines: 17, detail: "" },
    { name: "edges_odom.txt", required: false, status: "ok", lines: 11, detail: "" },
    { name: "edges_trav.txt", required: false, status: "ok", lines: 11, detail: "" },
  ],
  warnings: [],
  errors: [],
  checked_at: "2026-09-18T10:05:00+00:00",
};

export const session: Session = {
  id: "ses_1",
  region_id: "reg_1",
  name: "000",
  kind: "submap",
  source: "path",
  path: "/Titan/dataset/example/000",
  num_frames: 12,
  has_gt: false,
  has_gps: false,
  has_iqa: true,
  validation: validReport,
  created_at: "2026-09-18T10:05:00+00:00",
};

export const sessionInvalid: Session = {
  ...session,
  id: "ses_2",
  name: "broken",
  path: "/Titan/dataset/example/broken",
  has_iqa: false,
  validation: {
    ...validReport,
    ok: false,
    has_iqa: false,
    files: validReport.files.map((f) =>
      f.name === "gps_data.txt" ? { ...f, status: "missing", lines: null } : f,
    ),
    errors: ["gps_data.txt is required but missing"],
    warnings: ["edges_covis.txt is 3 lines short; those frames are dropped silently by the loader"],
  },
};

export const job: Job = {
  id: "job_20260918_120000_ab12",
  kind: "merge",
  queue: "gpu",
  status: "running",
  region_id: "reg_1",
  run_id: "run_20260918_120000_cd34",
  argv: ["/usr/bin/python", "python/map_merge_pipeline.py", "--submap_list", "/tmp/inputs.txt"],
  cwd: "/tmp/repo",
  env: { MKL_THREADING_LAYER: "GNU", PYTHONUNBUFFERED: "1" },
  cpu_list: "0-11",
  log_path: "/tmp/jobs/job_20260918_120000_ab12.log",
  pid: 4242,
  process_create_time: 1758196800,
  created_at: "2026-09-18T12:00:00+00:00",
  started_at: "2026-09-18T12:00:01+00:00",
  finished_at: null,
  returncode: null,
  crash_kind: null,
  error: null,
  progress: {
    step: 1,
    total: 2,
    stage_index: 7,
    stage: "pose_graph_optimization",
    completed_steps: 1,
    detail: "submap ses_2",
  },
};

export const steps: StepRecord[] = [
  {
    index: 0,
    session_id: "ses_1",
    dir_name: "merge_000_ses_1",
    status: "done",
    id_offset: 0,
    odom_nodes: 12,
    covis_nodes: 12,
    components: 1,
    registry_edges: 0,
    pgo_error_initial: 1.234,
    pgo_error_final: 0.456,
    started_at: "2026-09-18T12:00:01+00:00",
    finished_at: "2026-09-18T12:03:00+00:00",
  },
  {
    index: 1,
    session_id: "ses_2",
    dir_name: "",
    status: "running",
    id_offset: null,
    odom_nodes: null,
    covis_nodes: null,
    components: null,
    registry_edges: null,
    pgo_error_initial: 2.5,
    pgo_error_final: null,
    started_at: "2026-09-18T12:03:01+00:00",
    finished_at: null,
  },
];

export const run: Run = {
  id: "run_20260918_120000_cd34",
  region_id: "reg_1",
  name: "first merge",
  kind: "merge",
  parent: null,
  start_step: 0,
  session_ids: ["ses_1", "ses_2"],
  params: { pgo_robust: "gnc_gm", pgo_loop_sigma_trans: 0.1 },
  meta: {},
  status: "running",
  job_id: job.id,
  git_commit: "a49cdaa",
  num_steps_expected: 2,
  last_step_index: 0,
  final_dir: null,
  final_error: null,
  created_at: "2026-09-18T12:00:00+00:00",
  finished_at: null,
};

export const paramSpecs: ParamSpec[] = [
  {
    name: "pose_estimation_method",
    type: "str",
    default: "master",
    help: "Image matcher / pose estimator",
    group: "localization",
    choices: null,
    advanced: false,
  },
  {
    name: "vpr_match_seq_len",
    type: "int",
    default: 10,
    help: "Sequence length for VPR matching",
    group: "localization",
    choices: null,
    advanced: false,
  },
  {
    name: "pgo_robust",
    type: "choice",
    default: "gnc_gm",
    help: "Robust kernel for loop factors",
    group: "optimization",
    choices: ["none", "huber", "gnc_tls", "gnc_gm"],
    advanced: false,
  },
  {
    name: "pgo_loop_sigma_trans",
    type: "float",
    default: 0.1,
    help: "Loop factor translation sigma [m]",
    group: "optimization",
    choices: null,
    advanced: false,
  },
  {
    name: "use_iqa",
    type: "bool",
    default: true,
    help: "Cull keyframes by image quality",
    group: "culling",
    choices: null,
    advanced: false,
  },
  {
    name: "device",
    type: "choice",
    default: "cuda",
    help: "Torch device",
    group: "advanced",
    choices: ["cuda", "cpu"],
    advanced: true,
  },
];

export const summaries: StepSummary[] = [0, 1].map((k) => ({
  index: k,
  dir_name: k === 0 ? "merge_000_a" : "merge_001_b",
  session_id: k === 0 ? "ses_1" : "ses_2",
  status: "done",
  id_offset: k * 12,
  num_nodes: 12 * (k + 1),
  num_covis_nodes: 12 * (k + 1),
  num_new: 12,
  num_culled: k,
  component_sizes: [12 * (k + 1)],
  edge_counts: { odom: 11 + 12 * k, covis: 30 * (k + 1), trav: 11 * (k + 1) },
  history: k === 0 ? ({} as Record<string, number>) : { vpr: 6, gv: 6, ccm: 2, pgo: 1, low: 0, retained: 1 },
  precision: k === 0 ? [] : [0.5, 0.5, 1],
  recall: k === 0 ? [] : [0.4, 0.4, 0.2],
  loops: { total: 3 * k, new: 3 * k, hist: 0, accepted: k, rejected_new: 2 * k, overturned_hist: 0 },
  pgo_error_initial: k === 0 ? null : 2,
  pgo_error_final: k === 0 ? null : 0.7,
  max_displacement: 0.02 * k,
  num_moved: 0,
  duration_s: 3,
  has_dmatrix: k > 0,
  has_pre_pgo: true,
  ate_trans_rmse: k === 0 ? null : 0.612,
  ate_rot_rmse: k === 0 ? null : 1.23,
  ate_frames: k === 0 ? null : 24,
  ate_reason: k === 0 ? "pending" : null,
}));

export const evaluation: Evaluation = {
  eid: "final",
  status: "succeeded",
  ate_trans: 0.612,
  ate_rot: 1.23,
  frames: 24,
  created_at: "2026-09-18T12:10:00+00:00",
  job: { ...job, id: "job_eval_1", kind: "official_eval", queue: "cpu", status: "succeeded" },
  report_files: ["report_benchmark_eval_config/laptop_translation_rmse_opennavmap.txt", "report_benchmark_eval_config/plot.pdf"],
};

export const exportItem: ExportItem = {
  name: "map_20260918_121500",
  kind: "map",
  status: "succeeded",
  created_at: "2026-09-18T12:15:00+00:00",
  job_id: "job_export_1",
  steps: null,
  entries: 12,
  size: 2_621_440,
  sha256: "ab".repeat(32),
  verified: true,
};
